tls:
  truststore:
    fileName: "nonprod-truststore.ts"
    password: "![Xv1U+ItRpGmtee75UPjTYMl+TcPdBTULxrDvNOL3QII=]"
    type: "JKS"
  keystore:
    type: "JKS"
    fileName: "nonprod-keystore.jks"
    alias: "mule"
    keyPassword: "![Xv1U+ItRpGmtee75UPjTYMl+TcPdBTULxrDvNOL3QII=]"
    password: "![Xv1U+ItRpGmtee75UPjTYMl+TcPdBTULxrDvNOL3QII=]"

sapi:
  salesforce:
    host: ""
    port: "8092"
    maxConnections: "-1"
    timeout: "30000"
    client_id: "![]"
    client_secret: "![]"
    reconnect:
      frequency: "3000"
      attempts: "2"
    path:
      base: "/api"
      integrationStatus: "/integration/status"
      contacts: "/contacts"
      ping: "/ping"