tls:
  truststore:
    fileName: "nonprod-truststore.ts"
    password: "![Xv1U+ItRpGmtee75UPjTYMl+TcPdBTULxrDvNOL3QII=]"
    type: "JKS"
  keystore:
    type: "JKS"
    fileName: "nonprod-keystore.jks"
    alias: "mule"
    keyPassword: "![Xv1U+ItRpGmtee75UPjTYMl+TcPdBTULxrDvNOL3QII=]"
    password: "![Xv1U+ItRpGmtee75UPjTYMl+TcPdBTULxrDvNOL3QII=]"

sapi:
  salesforce:
    host: ""
    port: ""
    maxConnections: ""
    idle: ""
    username: "![]"
    password: "![]"
    path:
      status: "/integration/status"